name: Prune Workflows
on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: ["main"]
    paths: [".github/workflows/prune-workflows.yaml"]
  workflow_dispatch:
    inputs:
      days:
        description: "Days-worth of runs to keep for each workflow"
        required: true
        default: "30"
      minimum_runs:
        description: "Minimum runs to keep for each workflow"
        required: true
        default: "6"
      delete_workflow_pattern:
        description: "Name or filename of the workflow (if not set, all workflows are targeted)"
        required: false
      delete_workflow_by_state_pattern:
        description: "Filter workflows by state: active, deleted, disabled_fork, disabled_inactivity, disabled_manually"
        required: true
        default: "ALL"
        type: choice
        options:
          - "ALL"
          - active
          - deleted
          - disabled_inactivity
          - disabled_manually
      delete_run_by_conclusion_pattern:
        description: "Remove runs based on conclusion: action_required, cancelled, failure, skipped, success"
        required: true
        default: "ALL"
        type: choice
        options:
          - "ALL"
          - "Unsuccessful: action_required,cancelled,failure,skipped"
          - action_required
          - cancelled
          - failure
          - skipped
          - success
      dry_run:
        description: "Logs simulated changes, no deletions are performed"
        required: false

jobs:
  del_runs:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@78e5f2ddc08efcb88fbbee6cfa3fed770ba550c3 # v1.9.1
        id: app-token
        with:
          app-id: "${{ secrets.BOT_APP_ID }}"
          private-key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@4c9f24749b7996562658e3d6e10662489e22caca # v2
        with:
          token: "${{ steps.app-token.outputs.token }}"
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 10
